### ISSUE TITLE
java.lang.IllegalStateException: Can't compress a recycled bitmap

### ISSUE THREAD

**Issue by pys200603027** [arvinljw/SocialHelper#29]
如题，在点击分享的时候会出现此种情况，但不是每次都毕现了，是Bitmap回收引起的 

```java
at android.graphics.Bitmap.checkRecycled(Bitmap.java:392)
        at android.graphics.Bitmap.compress(Bitmap.java:1075)
        at net.arvin.socialhelper.SocialUtil.bmpToByteArray(SocialUtil.java:81)
        at net.arvin.socialhelper.WXHelper.addTitleSummaryAndThumb(WXHelper.java:348)
        at net.arvin.socialhelper.WXHelper.addWeb(WXHelper.java:322)
        at net.arvin.socialhelper.WXHelper.createMessage(WXHelper.java:252)
        at net.arvin.socialhelper.WXHelper.share(WXHelper.java:203)
        at net.arvin.socialhelper.SocialHelper.shareWX(SocialHelper.java:69)
        at io.liuliu.share.ShareHelper.shareMoment(ShareHelper.java:153)
```

**Comment by pys200603027** [comment]
补充下，稳定复出现在分享朋友圈的时候

**Comment by arvinljw** [comment]
怎么操作的呢？传的图片是资源还是本地图片，大小是多大呢

**Comment by arvinljw** [comment]
可能bmp和newBmp是同一个，那么在转换的时候就可能bitmap被释放的可能，我修改一下这个方法：

```
static byte[] bmpToByteArray(final Bitmap bmp, boolean needThumb) {
    Bitmap newBmp;
    if (needThumb) {
        int width = bmp.getWidth();
        int height = bmp.getHeight();
        if (width > height) {
            height = height * 150 / width;
            width = 150;
        } else {
            width = width * 150 / height;
            height = 150;
        }
        newBmp = Bitmap.createScaledBitmap(bmp, width, height, true);
    } else {
        newBmp = bmp;
    }
    ByteArrayOutputStream output = new ByteArrayOutputStream();
    newBmp.compress(Bitmap.CompressFormat.JPEG, 100, output);
    byte[] result = output.toByteArray();
    try {
        output.close();
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        if (!bmp.isRecycled()) {
            bmp.recycle();
        }
        if (!newBmp.isRecycled()) {
            newBmp.recycle();
        }
    }
    return result;
}
```

稍后发布新版，你再测试一下。

**Comment by arvinljw** [comment]
更新到v.1.2.2调整了这个问题，再试试？
